version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: crud-db.cpmyy02y07q0.us-east-2.rds.amazonaws.com
      DB_NAME: crud
      DB_USER: postgres
      DB_PASS: lK7xWD7fE2Ewuge
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lK7xWD7fE2Ewuge

    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crud"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
